# REFERENCE: https://yarnpkg.com/configuration/yarnrc

defaultSemverRangePrefix: ''

enableInlineBuilds: true

nmHoistingLimits: none

nodeLinker: node-modules

npmScopes:
  flex-development:
    npmAlwaysAuth: true
    npmAuthToken: ${GITHUB_TOKEN}
    npmRegistryServer: https://npm.pkg.github.com

patchFolder: ./patches

yarnPath: .yarn/releases/yarn-4.0.0-rc.14.cjs
